# Generated by Django 2.2.4 on 2019-08-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('img_url', models.CharField(default='bg1.jpg', max_length=50)),
                ('stock', models.IntegerField(default='0')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
