# Generated by Django 2.2.4 on 2019-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20190827_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='img_url',
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
