# Generated by Django 2.2.4 on 2019-09-05 09:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20190904_0809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Account',
        ),
    ]
