# Generated by Django 2.2.3 on 2019-07-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190704_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_email',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
