# Generated by Django 2.2.3 on 2019-07-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190704_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='img_url',
            field=models.CharField(default='bg1.jpg', max_length=50),
        ),
    ]
