# Generated by Django 2.2.4 on 2019-09-09 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190909_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 9, 11, 6, 17, 155695, tzinfo=utc)),
        ),
    ]
