# Generated by Django 2.2.3 on 2019-07-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
