# Generated by Django 2.2.3 on 2019-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190712_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='confirmed',
            field=models.IntegerField(default='0'),
        ),
    ]
