# Generated by Django 2.2.3 on 2019-07-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20190722_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='confirmed',
        ),
    ]
