# Generated by Django 2.2.3 on 2019-07-22 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_orderitem_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
    ]
