# Generated by Django 2.2.3 on 2019-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20190726_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='stock',
            field=models.IntegerField(default='0'),
        ),
    ]
